# Generated by Django 4.0.5 on 2022-06-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentteacher_remove_student_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentteacher',
            old_name='students',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentteacher',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
