# Generated by Django 4.0.5 on 2022-06-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentteacher',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(through='school.StudentTeacher', to='school.teacher'),
        ),
    ]
