# Generated by Django 4.1 on 2022-08-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_studentteacher_options_alter_student_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentteacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учетеля'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.AlterField(
            model_name='studentteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.student'),
        ),
    ]
